repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
    -   id: detect-private-key
    -   id: detect-aws-credentials
 - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        files: ^(app/|tests/)
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^(app/|tests/)
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        files: ^(app/|tests/)
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        files: ^(app/|tests/)