# To update env: conda env update --file environment.yml --prune

name: $NAME_CONDA_ENV
dependencies:
  - python=$PYTHON_VERSION
  # PRODUCTION
  - numpy
  - pandas
  - matplotlib
  - seaborn
  # DEVELOPMENT
  - black
  - isort
  - mypy
  - pylint
  - pytest
  - pytest-cov
  - pytest-sugar
